### ISSUE TITLE
Update instantiating of providers classes

### ISSUE THREAD

**Issue by EugeneButusov** [soomla/ios-profile#30]
Hi guys!
I write it after I completed the most of work implementing GPGS in Profile.
This issue relates to all Profile modules (except Cocos2dx, there is too simple).

The current scenario of SOOMLA Profile initialization (in context of providers initialization) is the following (in iOS, for example, Android is similar):
1) main class creates two instances of controllers - one for auth controller and other for social controller;
2) each controller looks for classes conforming specified interface (protocol in Obj-C terms): there is some hard-code thing in parent class (`ProviderLoader`) that checks if passed protocol is `ISocialProvider` - for `ISocialProvider` fetches all classes that implements `ISocialProvider`, and checks if current class conforms to `IAuthProvider` but doesn't conform to `ISocialProvider` otherwise. And, as I know, parent class shouldn't know anything about it successors.

It works fine before, but it breaks after `IGameServicesProvider` protocol was added. Here is some thoughts why it breaks:
1) Now we have `ISocialProvider` inherited from `IAuthProvider` and `IGameServicesProvider` inherited from `IAuthProvider`. So, comparsion in `ProviderLoader` defined in the point 2 above become too compicated;
2) Anyway, any provider can realize both `ISocialProvider` and `IGameServicesProvider`. For example, Google provider can implement Google+ functionality and GPGS functionality together. We can create separate providers for each services but I dont think that it's a good idea because in many cases this classes will use the same auth system (same classes, same instance variables). Moreover, Protocols (Interfaces) allows multiple inheritance and it can be useful for us. And the second argument against providers splitting that it may confuse users: why I have, for example GOOGLE_PLUS and GOOGLE_GPGS providers, though I can use only GOOGLE provider with flags that enables only social or gameservices part?
3) If we're allowing to use providers implementing multiple interfaces, the next question is appearing: how to determine an owner for current provider (by owner I mean controller that creates and manages provider class instance)? We can't create separate instances of provider for different controllers because it blocks correct work of authorization system of this provider (because this instances will have different set of instance variables).

Since controller classes has the similar code (instantiate providers, and for each method from SOOMLA Profile class find according provider and emit events in success/failure blocks used by selected provider), I suggest to exclude controllers classes and hold all instances of providers classes in `SoomlaProfile` class (as it already implemented in `Unity3D Profile`).

@vedi @borisspektor @refaelos, what do you think? I hope you'll understand my thoughts.

**Comment by vedi** [comment]
@EugeneButusov, thank you for detailed message. You're right, that code needs to be refactored. It was implemented at early times of Profile. I think it's better to ask @refaelos if Soomla is ready to the refactoring at this time. And only after that discuss how to do this in details. We can discuss that in Slack.

**Comment by EugeneButusov** [comment]
This issue was resolved in `v1.4.0`.
